// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl7Q1UHONVmXOyxwl_C_pD0Qi7pF1xMy4',
    appId: '1:726595998750:web:0524a8325d7cdcf5f20a0f',
    messagingSenderId: '726595998750',
    projectId: 'suvidha-admin-90b3c',
    authDomain: 'suvidha-admin-90b3c.firebaseapp.com',
    storageBucket: 'suvidha-admin-90b3c.firebasestorage.app',
    measurementId: 'G-6BSXD0KNJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyOJpZejIYSfai4DJ1GAVjjm6bihuRaAE',
    appId: '1:726595998750:android:a8f05c98f0e1a64bf20a0f',
    messagingSenderId: '726595998750',
    projectId: 'suvidha-admin-90b3c',
    storageBucket: 'suvidha-admin-90b3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3xLLVhgQNXJT48Vo3o8IeqR4PGyY8uxU',
    appId: '1:726595998750:ios:7e2a98a8bc98a91ff20a0f',
    messagingSenderId: '726595998750',
    projectId: 'suvidha-admin-90b3c',
    storageBucket: 'suvidha-admin-90b3c.firebasestorage.app',
    iosBundleId: 'com.example.suvidhaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3xLLVhgQNXJT48Vo3o8IeqR4PGyY8uxU',
    appId: '1:726595998750:ios:7e2a98a8bc98a91ff20a0f',
    messagingSenderId: '726595998750',
    projectId: 'suvidha-admin-90b3c',
    storageBucket: 'suvidha-admin-90b3c.firebasestorage.app',
    iosBundleId: 'com.example.suvidhaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl7Q1UHONVmXOyxwl_C_pD0Qi7pF1xMy4',
    appId: '1:726595998750:web:18f3a65c2dd7c9edf20a0f',
    messagingSenderId: '726595998750',
    projectId: 'suvidha-admin-90b3c',
    authDomain: 'suvidha-admin-90b3c.firebaseapp.com',
    storageBucket: 'suvidha-admin-90b3c.firebasestorage.app',
    measurementId: 'G-PMZJ4MSMD4',
  );
}
